export const carBrandAndModel = [
  {
    name: "Toyota",
    model : [
      "Vios",
      "Altis",
      "Camry",
      "Fortuner",
      "C-HR",
      "4Runner",
      "86GT",
      "Alphard",
      "altezza",
      "Aristo",
      "Avanza",
      "BB",
      "Caldina",
      "Carib",
      "Carina",
      "Cavalier",
      "Celica",
      "Century",
      "Commuter",
      "Corolla",
      "Corona",
      "Cressida",
      "Crown",
      "Dyna",
      "Emina",
      "Estima",
      "Esquire",
      "Gaia",
      "Glanza",
      "Grand Hiace",
      "Granvia",
      "Harrier",
      "Hiace",
      "Hilux Hero",
      "Hilux Mighty-X",
      "Hilux Revo",
      "Hulix Sport Rider",
      "Hilux Tiger",
      "Hilux Tiger D4D",
      "Hilux Vigo",
      "Hilux Vigo Champ",
      "Hilux Vigo D4D",
      "Innova",
      "Ipsum",
      "IQ",
      "IST",
      "Kluger",
      "Land Cruiser",
      "Levin",
      "Liace",
      "Liteac",
      "LN",
      "Lucida",
      "Land Cruiser Prado",
      "Marino",
      "Mark II",
      "Mark X",
      "MR-S",
      "MR2",
      "Paseo",
      "Porte",
      "Previa",
      "Prius",
      "RAV 4",
      "Regius",
      "Sera",
      "Sienna",
      "Sienta",
      "Soarer",
      "Soluna",
      "Spacio",
      "Sport Cruiser",
      "Sport Rider",
      "SR5",
      "Starlet",
      "Super Custom",
      "Supra",
      "Surf",
      "Tercel",
      "Toyopet",
      "Townace Noah",
      "Tunno",
      "Ventury",
      "Vista",
      "Vitz",
      "Voltz",
      "Voxy",
      "Vellfire",
      "Wish",
      "Yaris",
      "Yaris ATIV",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Honda",
    model : [
      "City",
      "Civic",
      "Jazz",
      "HR-V",
      "CR-V",
      "Accord",
      "Accord Hybrid",
      "Airwave",
      "Ascot",
      "Avancier",
      "Brio",
      "Brio Amaze",
      "BR-V",
      "CR-X",
      "Domani",
      "Dunk",
      "Edix",
      "Elysion",
      "Freed",
      "Insight",
      "Inspire",
      "Integra",
      "Legend",
      "Mobilio",
      "NSX",
      "Odyssey",
      "Prelude",
      "S2000",
      "Stepwagon",
      "Stream",
      "Tourmaster",
      "Vigor",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Nissan",
    model : [
      "Almera",
      "March",
      "Teana",
      "X-Trail",
      "Navara",
      "180 SX",
      "200 SX",
      "300 ZX",
      "350Z",
      "370Z",
      "Atlas",
      "BIG-M",
      "FRONTIER",
      "BIG-M FRONTIER NAVARA",
      "Bluebird",
      "Caravan",
      "Cedric",
      "Cefiro",
      "Cima",
      "Cube",
      "Datsuns",
      "Elgrand",
      "Fairlady",
      "Fairlady-Z",
      "Fingaro",
      "Fuga",
      "Gloria",
      "GT-R",
      "Infiniti",
      "Juke",
      "Largo",
      "Laurel",
      "Leopard",
      "Leaf",
      "Livina",
      "Maxima",
      "Murano",
      "Note",
      "NP300-NAVARA",
      "NV",
      "NX",
      "Patrol",
      "Praire",
      "Presea",
      "President",
      "Primera",
      "Pulsa",
      "Safari",
      "SD",
      "Sentra",
      "Serena",
      "Silvia",
      "Skyline",
      "Stanza",
      "Sunny",
      "Sylphy",
      "Terra",
      "Terrano",
      "Tiida",
      "Urvan",
      "Vanette",
      "Violet",
      "Xciter",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Mitsubishi",
    model : [
      "Mirage",
      "Triton",
      "Pajero",
      "Pajero Sport",
      "Attrage",
      "Xpander",
      "3000 GTO",
      "Aerobody",
      "Airtrek",
      "Astron",
      "Champ",
      "Colt",
      "Cyclone",
      "Delica",
      "Diamante",
      "Eclipse",
      "Evolution",
      "FTO",
      "G-WAGON",
      "Galant",
      "Jeep",
      "L200-Cyclone",
      "L200-Strada",
      "L300",
      "Lancer",
      "Lancer EX",
      "Outlander",
      "Space Runner",
      "Space Wagon",
      "Strada G Wagon",
      "Strada Grandis",
      "Ultima",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Mercedes-Benz",
    model : [
      "C-Class",
      "E-Class",
      "CLA-Class",
      "CLS-Class",
      "GLA-Class",
      "190",
      "200",
      "212",
      "220",
      "230",
      "240",
      "250",
      "280",
      "300",
      "350",
      "380",
      "400",
      "450",
      "500",
      "560",
      "600",
      "A-Class",
      "B-Class",
      "CL-CLass",
      "CLC-Class",
      "CLK-Class",
      "G-Class",
      "Gl-Class",
      "GLB-Class",
      "GLC-Class",
      "GLE-Class",
      "GLS-Class",
      "MB-Class",
      "ML-Class",
      "R-Class",
      "S-Class",
      "SL-Class",
      "SLC-Class",
      "SLK-Class",
      "Smart",
      "V-Class",
      "Vito",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Isuzu",
    model : [
      "D-MAX",
      "MU-X",
      "MU-7",
      "V-Cross",
      "Spark Ex",
      "Adventure",
      "Adventure Master",
      "Aska",
      "Buddy",
      "Cab 4",
      "Cameo",
      "Dragon Eye",
      "Dragon Power",
      "Faster",
      "Gemini",
      "Geo Storm",
      "Grand Adventure",
      "Heno",
      "Hi-Lander",
      "Impulse",
      "KB ปี 84-90",
      "MU",
      "Rodeo",
      "Spacecab",
      "Supreme",
      "TFR ปี 91-97",
      "Trooper",
      "Victor III",
      "Vega",
      "Vertex",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "BMW",
    model : [
      "Series 3",
      "Series 5",
      "X1",
      "X3",
      "Z4",
      "Classic Car",
      "I3",
      "I8",
      "L7",
      "M2",
      "M3",
      "M4",
      "M5",
      "M6",
      "MINI",
      "Series 1",
      "Series 2",
      "Series 4",
      "Series 6",
      "Series 7",
      "Series 8",
      "X2",
      "X4",
      "X5",
      "X6",
      "X7",
      "Z3",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Mazda",
    model : [
      "Mazda2 Elegance",
      "Mazda2 Sport",
      "Mazda3",
      "CX-3",
      "CX-5",
      "121",
      "323",
      "323-Astina",
      "626",
      "808",
      "929",
      "B2000",
      "B2500",
      "BT-50",
      "BT-50 Pro",
      "Capella",
      "Cronos",
      "CX-7",
      "CX-8",
      "CX-9",
      "Familia",
      "Familia Coupe",
      "Fighter",
      "Lantis",
      "Marathon",
      "Maxnum",
      "Maxda5",
      "Mazda6",
      "MPV",
      "MX-5",
      "RX-3",
      "RX-7",
      "RX-8",
      "Thunder",
      "Tribute",
      "Xedos 9",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Ford",
    model : [
      "Ranger",
      "Fiesta",
      "Everest",
      "Focus",
      "Ecosport",
      "Aspire",
      "Cadillac Fleetwood",
      "Capri",
      "Cortina",
      "Escape",
      "Explorer",
      "Falcon",
      "Festiva",
      "GT",
      "Laser",
      "Lincoln",
      "Marathon",
      "Mondeo",
      "Mustang",
      "Sierra",
      "Telstar",
      "Territory",
      "thunderbird",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Chevrolet",
    model : [
      "Captiva",
      "Trailblazer",
      "Colorado",
      "Cruze",
      "Aveo",
      "Allroader",
      "Astro",
      "Camaro",
      "Chevy Van",
      "Corvette",
      "Express",
      "Impala",
      "Lumina",
      "Optra",
      "S10",
      "Savana",
      "Sonic",
      "Spin",
      "Zafira",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Alfa Romeo",
    model : [
      "Alfa Romeo155",
      "Alfa Romeo156",
      "Alfa Romeo166",
      "Alfa Romeo1750",
      "Giulia",
      "Giulietta",
      "GT",
      "GTV",
      "Spider",
      "Spider 2000",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Aston Martin",
    model : [
      "Cygnet",
      "DB7 Vantage",
      "DB9",
      "DB11",
      "DBS Superleggera",
      "Rapide",
      "V12 Vantage",
      "V8 Vantage",
      "Vantage S",
      "Virage",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Audi",
    model : [
      "Audi 100",
      "Audi 80",
      "Audi A1",
      "Audi A3",
      "Audi A4",
      "Audi A5",
      "Audi A6",
      "Audi A7",
      "Audi A8",
      "Audi Q2",
      "Audi Q5",
      "Audi Q7",
      "Audi Q8",
      "Audi R8",
      "Audi RS3",
      "Audi RS5",
      "Audi RS6",
      "Audi S3",
      "Audi S4",
      "Audi S5",
      "Audi S6",
      "Audi TT",
      "Audi TT RS",
      "Audi TTS",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Toyo",
    model : [
      "FX4",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Bently",
    model : [
      "Arnage",
      "Bentayga",
      "Brooklands",
      "Continental",
      "Flying Spur",
      "Mulsanne",
      "Turbo",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Cardillac",
    model : [
      "CTS-V",
      "Eldorado",
      "Escalade",
      "Fleetwood",
      "Sedan Deville",
      "Seville",
      "STS",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Chrysler",
    model : [
      "300c",
      "Chrysler 300M",
      "Neon",
      "PT Cruiser",
      "Voyager",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Citroen",
    model : [
      "AX",
      "Berlingo",
      "C3",
      "C5",
      "C8",
      "CX20",
      "DS3",
      "DS4",
      "Jumper",
      "Xantia",
      "Xsara",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Daewoo",
    model : [
      "Espero",
      "Nexia",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Daihatsu",
    model : [
      "Atrai",
      "Atrai Wagon",
      "Copen",
      "Hijet",
      "Midget II",
      "Mira",
      "Move",
      "Opti",
      "Terios",
      "YRV",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "DFM",
    model : [
      "Mini Van",
      "Mini Truck",
      "V27",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Ferrari",
    model : [
      "360 Modena",
      "360 Spider",
      "360 Stradale",
      "365 Daytona",
      "430 Scudera",
      "458 italia",
      "458 SPECIALE",
      "488 GTB",
      "512 TR",
      "575M Maranello",
      "599 GTB",
      "612 Scaglietti",
      "California",
      "F12 BERLINETTA",
      "F355 Berlinetta",
      "F430",
      "F430 Challenge",
      "F430 Spider",
      "Ferrari 348",
      "FF",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Fiat",
    model : [
      "695 Ferrari",
      "Fiat 1100",
      "Fiat 131",
      "Fiat 1500",
      "Fiat 500",
      "Punto",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "GMC",
    model : [
      "Savana",
      "SIERRA DENALI",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Hummer",
    model : [
      "Hummer H2",
      "Hummer H3",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Hyundai",
    model : [
      "Accent",
      "Elantra",
      "Excel",
      "Grand Starex",
      "H-1",
      "IONIQ",
      "KONA",
      "Sonata",
      "Sprint",
      "Tiburon",
      "Tucson",
      "Veloster",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Jaguar",
    model : [
      "Daimler",
      "E-PACE",
      "F-PACE",
      "F-Type",
      "I-PACE",
      "MK2",
      "S-Type",
      "Sovereign",
      "X-Type",
      "XE",
      "XF-Series",
      "XJ-Series",
      "XJL-Series",
      "XJR",
      "XK-Series",
      "XK140",
      "XKR",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Jeep",
    model : [
      "Cherokee",
      "Grand Cherokee",
      "Wrangler",
      "willy",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Kia",
    model : [
      "Carens",
      "Carnival",
      "Grand Carnival",
      "Grand Sportage",
      "Jumbo",
      "Picanto",
      "Pregio",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Lamborghini",
    model : [
      "Aventador",
      "Diablo",
      "Gallardo",
      "Huracan",
      "Murcielago",
      "Urus",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Lancia",
    model : [
      "Beta",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Land Rover",
    model : [
      "defender",
      "Discovery",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Velar",
      "Series. 1",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Lexus",
    model : [
      "Aristo",
      "CT200h",
      "ES300",
      "GS250",
      "GS300",
      "GS350",
      "GS450",
      "IS F",
      "IS200",
      "IS250",
      "IS250C",
      "IS300",
      "IS400",
      "IS430",
      "LS460",
      "LS460L",
      "LS500",
      "LS600hl",
      "LX460",
      "LX470 CYGNUS",
      "LX570",
      "NX300h",
      "RC",
      "RX270",
      "RX300",
      "RX330",
      "RX350",
      "RX450h",
      "SC430",
      "Soarer",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Lotus",
    model : [
      "Elan",
      "Elise",
      "Esprit",
      "Evora",
      "Exige",
      "Sport",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Maserati",
    model : [
      "Ghibli",
      "GranTurismo",
      "GT Coupe",
      "Levante",
      "Quattroporte",
      "Spyder",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "McLaren",
    model : [
      "570S",
      "650S",
      "720S",
      "MP4",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "MG",
    model : [
      "Extender",
      "GS",
      "HS",
      "MG3",
      "MG5",
      "MG6",
      "MGB",
      "MGF",
      "Midget MK",
      "V80",
      "ZS",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Mini",
    model : [
      "AUSTIN CLASSIC",
      "AUSTIN MINI",
      "CLUBMAN",
      "CONVERTIBLE",
      "COOPER",
      "COOPER 3 DOOR HATCH",
      "COOPER 5 DOOR HATCH",
      "COUNTRYMAN",
      "JOHN COOPER WORK",
      "ONE",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Opel",
    model : [
      "Astra",
      "Calibra",
      "Commodore",
      "Corsa",
      "Kapitan",
      "Omega",
      "Vectra",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Peugeot",
    model : [
      "Bipper",
      "Partner",
      "Peugeot205",
      "Peugeot206",
      "Peugeot207",
      "Peugeot305",
      "Peugeot306",
      "Peugeot307",
      "Peugeot308",
      "Peugeot405",
      "Peugeot406",
      "Peugeot407",
      "Peugeot408",
      "Peugeot504",
      "Peugeot505",
      "Peugeot508",
      "Peugeot605",
      "Peugeot607",
      "Peugeot807",
      "Peugeot1007",
      "Peugeot3008",
      "Peugeot5008",
      "RCZ",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Porsche",
    model : [
      "718",
      "911 Carrera",
      "911 Carrera S",
      "911 GT2",
      "911 Sport Classic",
      "Targa 4S",
      "Turbo",
      "928",
      "993 Carrera",
      "993 Targa",
      "996 Carrera",
      "996 GT3",
      "997 Carrera",
      "Boxster",
      "Carrera",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
      "Taycan",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Proton",
    model : [
      "Exora",
      "Gen-2",
      "Neo",
      "Persona",
      "Preve",
      "Saga",
      "Satria",
      "Savvy",
      "Waja",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Renault",
    model : [
      "R-19",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Rolls-Royce",
    model : [
      "Corniche II",
      "Cullinan",
      "Dawn",
      "Ghost",
      "Phantom",
      "Silver Shadow II",
      "Silver Spirit II",
      "Silver Spur II",
      "Silver Spur III",
      "Wraith",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Rover",
    model : [
      "220 Coupe",
      "623",
      "75",
      "827 Sterling",
      "MINI",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "SAAB",
    model : [
      "43713",
      "900",
      "9000",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Skoda",
    model : [
      "Fabia",
      "Octavia",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Smart",
    model : [
      "City",
      "Forfour",
      "Fortwo",
      "Roadster",
      "smart",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Ssangyong",
    model : [
      "Actyon",
      "Chairman",
      "Kyron",
      "Musso",
      "Rexton",
      "Stavic",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Subaru",
    model : [
      "BRZ",
      "Forester",
      "GLT",
      "Impreza",
      "Legacy",
      "Outback",
      "R2",
      "WRX",
      "XV",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Suzuki",
    model : [
      "Alto",
      "APV",
      "Cappuccino",
      "Caribian",
      "Carry",
      "Cervo",
      "Celerio",
      "Ciaz",
      "Ertiga",
      "Esteem",
      "Grand Vitara",
      "Jimmy",
      "Swift",
      "SX4",
      "Vitara",
      "Wagon R",
      "Wagon R Plus",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "TATA",
    model : [
      "Super ACE",
      "Xenon",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Tesla",
    model : [
      "Model-3",
      "Model S",
      "Model-X",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Thairung",
    model : [
      "Transformer",
      "TR-Adventure",
      "TR-Allroader",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Volkswagen",
    model : [
      "Beetle",
      "Caravelle",
      "Classic Car",
      "Corrado",
      "Golf",
      "New Beetle",
      "Passat",
      "Polo",
      "Scirocco",
      "Sharan",
      "Touareg",
      "Transporter",
      "Vento",
      "รุ่นอื่นๆ"
  ]
  },
  {
    name: "Volvo",
    model : [
      "440",
      "460",
      "480",
      "740",
      "850",
      "940",
      "960",
      "C30",
      "C70",
      "Classic Car",
      "S40",
      "S60",
      "S70",
      "S80",
      "S90",
      "V40",
      "V50",
      "V70",
      "V60",
      "V90",
      "XC40",
      "XC60",
      "XC70",
      "XC90",
      "รุ่นอื่นๆ"
  ]
  },
  { name: "ยี่ห้ออื่นๆ", model: [] },
]
