import { Platform } from 'react-native';

export const consumableSkus = Platform.select({
    ios: [
        'com.mixxer.test.coin.10',
        'com.mixxer.test.coin.20',
        'com.mixxer.test.coin.30',
        'com.mixxer.test.coin.40',
        'com.mixxer.test.coin.50',
        'com.mixxer.test.coin.60',
        'com.mixxer.test.coin.70',
        'com.mixxer.test.coin.80',
        'com.mixxer.test.coin.90',
        'com.mixxer.test.coin.100',
        'com.mixxer.test.coin.110',
        'com.mixxer.test.coin.120',
        'com.mixxer.test.coin.130',
        'com.mixxer.test.coin.140',
        'com.mixxer.test.coin.150',
        'com.mixxer.test.coin.160',
        'com.mixxer.test.coin.170',
        'com.mixxer.test.coin.180',
        'com.mixxer.test.coin.190',
        'com.mixxer.test.coin.200',
    ],
    android: [
        'com.mixxer.test.coin.10',
        'com.mixxer.test.coin.20',
        'com.mixxer.test.coin.30',
        'com.mixxer.test.coin.40',
        'com.mixxer.test.coin.50',
        'com.mixxer.test.coin.60',
        'com.mixxer.test.coin.70',
        'com.mixxer.test.coin.80',
        'com.mixxer.test.coin.90',
        'com.mixxer.test.coin.100',
        'com.mixxer.test.coin.110',
        'com.mixxer.test.coin.120',
        'com.mixxer.test.coin.130',
        'com.mixxer.test.coin.140',
        'com.mixxer.test.coin.150',
        'com.mixxer.test.coin.160',
        'com.mixxer.test.coin.170',
        'com.mixxer.test.coin.180',
        'com.mixxer.test.coin.190',
        'com.mixxer.test.coin.200',
    ]
});