export const contestCategoryArr = [
  { name: "ท่องเที่ยว/กิจกรรม", engName: "Travel and Activity" },
  { name: "เกม", engName: "Game" },
  { name: "ขำขัน", engName: "Comedy" },
  { name: "หนังสือ/งานเขียน", engName: "Book and Writing" },
  { name: "ทีวี", engName: "TV" },
  { name: "น่ารัก", engName: "Cute" },
  { name: "ดนตรี", engName: "Music" },
  { name: "ความงาม", engName: "Beauty" },
  { name: "ศิลปะ/ดีไซน์", engName: "Art and Design" },
  { name: "แฟชั่น", engName: "Fashion" },
  { name: "การเงิน/ธุรกิจ", engName: "Finance and Business" },
  { name: "อาหาร", engName: "Food" },
  { name: "กีฬา", engName: "Sport" },
  { name: "สุขภาพ", engName: "Health" },
  { name: "การศึกษา", engName: "Education" },
  { name: "แม่และเด็ก", engName: "Parenting" },
  { name: "เรื่องแปลก", engName: "Strange" },
  { name: "คอหวย", engName: "Lottery" },
  { name: "สายบุญ", engName: "Merit" },
  { name: "ความเชื่อ/ไสยศาสตร์", engName: "Superstition" },
  { name: "คนรักสัตว์", engName: "Animal" },
  { name: "ภาพยนต์/แอนิเมชั่น", engName: "Movie and Animation" },
  { name: "เทคโนโลยี/วิทยาศาสตร์", engName: "Technology and Science" },
  { name: "ฟรีสไตล์", engName: "FreeStyle" },
]

