export const phoneBrand = [
  { name: "iPhone" },
  { name: "Samsung" },
  { name: "AIS" },
  { name: "ASUS" },
  { name: "Blackberry" },
  { name: "dtac" },
  { name: "Google" },
  { name: "HTC" },
  { name: "Huawei" },
  { name: "i-mobile" },
  { name: "Lenovo" },
  { name: "LG" },
  { name: "Moto" },
  { name: "Nokia" },
  { name: "Oneplus" },
  { name: "OPPO" },
  { name: "SONY" },
  { name: "TRUE" },
  { name: "TWZ" },
  { name: "Vivo" },
  { name: "Wiko" },
  { name: "Xiaomi" },
  { name: "ยี่ห้ออื่นๆ" }
]
