export const shopCategory = [
  {
    name: "เวชภัณและการแพทย์",
    engName: "medical",
    iconName: "medical-bag",
    iconType: "material-community",
    picture: require("../../assets/pic/medical.jpg"),
  },
  {
    name: "ก่อสร้าง-เครื่องมือช่าง",
    engName: "construction",
    iconName: "ios-construct",
    iconType: "ionicon",
    picture: require("../../assets/pic/tools.jpg"),
  },
  {
    name: "การศึกษา",
    engName: "education",
    iconName: "graduation-cap",
    iconType: "font-awesome",
    picture: require("../../assets/pic/book.jpg"),
  },
  {
    name: "ความงาม",
    engName: "beauty",
    iconName: "magnifying-glass",
    iconType: "foundation",
    picture: require("../../assets/pic/beauty.jpg"),
  },
  {
    name: "ป้าย สิ่งพิมพ์และโฆษณา",
    engName: "advertisement",
    iconName: "sign-text",
    iconType: "material-community",
    picture: require("../../assets/pic/billboard.jpg"),
  },
  {
    name: "กฎหมาย",
    engName: "law",
    iconName: "business-center",
    picture: require("../../assets/pic/law.jpg"),
  },
  {
    name: "สัตว์และเกษตร",
    engName: "agriculture",
    iconName: "tractor",
    iconType: "material-community",
    picture: require("../../assets/pic/cow.jpg"),
  },
  {
    name: "การเงิน",
    engName: "finance",
    iconName: "finance",
    iconType: "material-community",
    picture: require("../../assets/pic/finance.jpg"),
  },
  {
    name: "แฟชั่น",
    engName: "fashion",
    iconName: "tshirt-crew",
    iconType: "material-community",
    picture: require("../../assets/pic/fashion.jpg"),
  },
  {
    name: "ของใช้ในบ้าน",
    engName: "homeApplicant",
    iconName: "fridge",
    iconType: "material-community",
    picture: require("../../assets/pic/furniture.jpg"),
  },
  {
    name: "ที่พัก",
    engName: "hotel",
    iconName: "hotel",
    iconType: "font-awesome",
    picture: require("../../assets/pic/hotel.jpg"),
  },
  {
    name: "ทัวร์และท่องเที่ยว",
    engName: "tourism",
    iconName: "airplane",
    iconType: "material-community",
    picture: require("../../assets/pic/ferry.jpg"),
  },
  {
    name: "อาหารและเครื่องดื่ม",
    engName: "foodAndDrink",
    iconName: "food",
    iconType: "material-community",
    picture: require("../../assets/pic/food.jpg"),
  },
  {
    name: "ไอที",
    engName: "it",
    iconName: "tablet-cellphone",
    iconType: "material-community",
    picture: require("../../assets/pic/it.jpg"),
  },
  {
    name: "ยานยนต์",
    engName: "automotive",
    iconName: "engine",
    iconType: "material-community",
    picture: require("../../assets/pic/motor.jpg"),
  },
  {
    name: "กีฬาและสุขภาพ",
    engName: "sport",
    iconName: "soccer",
    iconType: "material-community",
    picture: require("../../assets/pic/fitness.jpg"),
  },
  {
    name: "แม่และเด็ก",
    engName: "parenting",
    iconName: "baby-buggy",
    iconType: "material-community",
    picture: require("../../assets/pic/parenting.jpeg"),
  },
  {
    name: "การกุศลและมูลนิธิ",
    engName: "charity",
    iconName: "charity",
    iconType: "material-community",
    picture: require("../../assets/pic/foundation.jpg"),
  },
  {
    name: "อื่นๆ",
    engName: "other",
    iconName: "shopping-basket",
    iconType: "font-awesome",
    picture: require("../../assets/pic/miscellaneous.png"),
  }
]
