export const linking = {
  prefixes: ['https://mix-xer.com', 'mix-xer://'],
  config: {
    screens: {
      Main: {
        path: 'main',
        screens: {
          NewFeed: 'feed',
          News: 'news',
          Subscription: 'subscription',
          Market: 'market',
          Notification: 'notification',
          Menu: 'menu',
        },
      },
      Register: 'register',
      Login: 'login',
      ForgotPassword: 'forgot-password',
      ResetPassword: 'reset-password',
      ManageAd: 'manage-ad',
      Post: 'post',
      NewsPost: 'news-post',
      GroupPost: 'group-post',
      UserPost: 'user-post',
      // Category: 'category',
      // NewsCategory: 'news-category',
      // Postcategory: 'post-category',
      MyProfile: 'myprofile',
      UserProfile: 'user-profile',
      EditUser: 'edit-user',
      Map: 'map',
      GroupList: 'group-list',
      FollowedList: 'followed-list',
      GroupMember: 'group-member',
      GroupRoom: 'group-room',
      CreateGroup: 'create-group',
      EditGroup: 'edit-group',
      Ad: 'ad',
      ManageShop: 'manage-shop',
      CreateSponsor: 'create-sponsor',
      UpdateSponsor: 'update-sponsor',
      CreatePromote: 'create-promote',
      UpdatePromote: 'update-promote',
      ShopFeed: 'shop-feed',
      Shop: 'shop',
      EditShop: 'edit-shop',
      ShopImage: 'shop-image',
      Review: 'review',
      PostShopPicture: 'post-shop-picture',
      PostShopDetail: 'post-shop-detail',
      ProductFeed: 'product-feed',
      Product: 'product',
      YourProduct: 'your-product',
      ProductOption: 'product-option',
      PostProductPicture: 'post-product-picture',
      PostProductDetail: 'post-product-detail',
      Search: 'search',
      BuyCoin: 'buy-coin',
      Detail: 'detail',
      Nomatch: "*",
    },
  }
};